feetech_ros2_interface:
  ros__parameters:
    node:
      frequency: 10.0

    driver:
      port_name: "/dev/ttyUSB0"
      baud_rate: 1000000
      frequency: 50.0

    servos:
      ids: [11, 12, 21, 22, 31, 32, 41, 42] #, 2, 3, 4, 5, 6, 7, 8]
      operating_modes: [4, 4, 4, 4, 4, 4, 4, 4] # Velocity mode 2, continuous position mode 4
      homing_modes: [0, 0, 0, 0, 0, 0, 0, 0] #, 0, 0, 0, 0, 0, 0, 0]
      max_speeds: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0] #, 100., 100., 100., 100., 100., 100., 100.]
      max_currents: [100., 100., 100., 100., 100., 100., 100., 100.] #, 100., 100., 100., 100., 100., 100., 100.]

    effort_average_window_size: 25
